#this task builds tarball from the whole repo

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
- name: app-source
outputs:
- name: build-dir

run:
  path: app-source/ci/build.sh
