#this task builds tarball from the whole repo

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
- name: app-source
- name: version
outputs:
- name: build_dir

params:
  VERSION: version/number

run:
  path: app-source/ci/build.sh
